export enum EGamer {
    BLACK = "BLACK",
    WHITE = "WHITE"
}

export enum GamerStatus {
    CONNECTED = "CONNECTED",
    DISCONNECTED = "DISCONNECTED",
    EXITED = "EXITED"
}

export enum SubscriptionMessages {
    GAME_MOVED = "GAME_MOVED",
    GAME_STARTED = "GAME_STARTED",
    GAME_RESTARTED = "GAME_STARTED",
    GAME_UPDATED = "GAME_UPDATED",
    GAMERS_STONE_COUNT_UPDATED = "GAMERS_STONE_COUNT_UPDATED",
    GAMER_CONNECTED = "GAMER_CONNECTED",
    GAMER_DISCONNECTED = "GAMER_DISCONNECTED"
}