export enum EGamer {
    BLACK = "BLACK",
    WHITE = "WHITE"
}

export enum EGamerStatus {
    CONNECTED = "CONNECTED",
    DISCONNECTED = "DISCONNECTED",
}

export enum ESubscriptionMessages {
    GAME_MOVED = "GAME_MOVED",
    GAME_STARTED = "GAME_STARTED",
    GAME_UPDATED = "GAME_UPDATED",
    GAMERS_STONE_COUNT_UPDATED = "GAMERS_STONE_COUNT_UPDATED",
    GAMER_CONNECTION = "GAMER_CONNECTION",
}

export enum GRAPHQL_ERROR_CODES {
    GAME_NOT_FOUND = 'GAME_NOT_FOUND',
    MOVES_NOT_FOUND = 'MOVES_NOT_FOUND',
    ROOM_FULL = 'ROOM_FULL',
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    BAD_USER_INPUT = "BAD_USER_INPUT",
    DUPLICATE_MOVE = "DUPLICATE_MOVE"
}